# Generated by Django 4.2.21 on 2025-08-02 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("agri_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("update_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea", max_length=7, verbose_name="グループカラー"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "グループプロフィール",
                "verbose_name_plural": "グループプロフィール",
                "db_table": "group_profile",
                "db_table_comment": "グループプロフィール",
            },
        ),
    ]
