# Generated by Django 4.2.23 on 2025-08-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agri_app", "0002_groupprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDao",
        ),
    ]
