# Generated by Django 4.2.23 on 2025-08-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_app", "0003_delete_userdao"),
    ]

    operations = [
        migrations.CreateModel(
            name="StyleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="設定名")),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("default", "デフォルト（KUUMA風）"),
                            ("dark", "ダークテーマ"),
                            ("nature", "自然テーマ"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="スタイル",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="アクティブ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "スタイル設定",
                "verbose_name_plural": "スタイル設定",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
    ]
