# Generated by Django 4.2.23 on 2025-08-03 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agri_app', '0004_stylesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylesettings',
            options={'verbose_name': 'スタイル設定', 'verbose_name_plural': 'スタイル設定'},
        ),
        migrations.AlterModelTableComment(
            name='stylesettings',
            table_comment='スタイル設定',
        ),
        migrations.RemoveField(
            model_name='stylesettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stylesettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stylesettings',
            name='style',
        ),
        migrations.RemoveField(
            model_name='stylesettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stylesettings',
            name='active_style',
            field=models.CharField(choices=[('base', 'ベーススタイル'), ('kuuma', 'KUUMAスタイル'), ('dark', 'ダークテーマ'), ('colorful', 'カラフルテーマ')], default='base', max_length=20, verbose_name='アクティブスタイル'),
        ),
        migrations.AddField(
            model_name='stylesettings',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stylesettings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='stylesettings',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='デフォルト設定'),
        ),
        migrations.AddField(
            model_name='stylesettings',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stylesettings',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='設定名'),
        ),
        migrations.AlterModelTable(
            name='stylesettings',
            table='style_settings',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '通常'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=10, verbose_name='優先度')),
                ('start_date', models.DateTimeField(verbose_name='表示開始日時')),
                ('end_date', models.DateTimeField(verbose_name='表示終了日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('target_groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='通知先グループ')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'db_table': 'announcement',
                'db_table_comment': 'お知らせ',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
