# Generated by Django 4.2.23 on 2025-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_app", "0005_add_announcement_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="is_all_groups",
            field=models.BooleanField(
                default=False, verbose_name="全てのグループに通知"
            ),
        ),
    ]
