# Generated by Django 4.2.23 on 2025-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_app", "0006_announcement_is_all_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="メール送信済み"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="メール送信日時"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="send_email",
            field=models.BooleanField(default=False, verbose_name="メール送信"),
        ),
    ]
