# Generated by Django 4.2.23 on 2025-08-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agri_app", "0004_announcement_email_fields"),
        (
            "agri_app",
            "0007_announcement_email_sent_announcement_email_sent_at_and_more",
        ),
    ]

    operations = []
